### ISSUE TITLE
Разработка драйвера ДПТ

### ISSUE THREAD

**Issue by Doraepod** [lsd-maddrive/mishanya-bot-project#23]
Задача разработать 3 версии драйвера:
  - Без радиатора
  - С радиатором
  - Без радиатора, с логикой
Разные варианты стоит делать последовательно, и полностью решить все сложности с первой версией, прежде чем приступать ко второй.

На что обращать внимание:

1) Наличие паразитных индуктивностей при сложных путях дорожек. На [Хабре](https://habr.com/ru/post/414141/) есть вроде бы дельная статья по разводке, но без фанатизма.
2) Силовые дорожки делать **ЖИРНЫМИ** и не покрывать лаком. Самый минимум - 6мм.
3) Разделить цифровую и силовую часть. То есть входы с мк с одной стороны, силовые контакты с другой. Для цифровой части использовать угловой JST, для силовых выводов оставить металлизированные отверстия диаметром 3мм.
4) Монтажные отверстия изолированы от земли/дорожек.
5) Печатать разведенную плату на бумаге (в масштабе 1к1) и прикладывать элементы.
6) Шелкография. Должно быть очевидно к какому элементу относится подпись. Наличие ключа для всех элементов, где это применимо.

**Comment by KaiL4eK** [comment]
До конца недели

**Comment by serykhelena** [comment]
@pavelrepin99 @Doraepod А эта задача ещё не закончена? Вроде же уже платы заказаны?

**Comment by Doraepod** [comment]
@serykhelena Закончена, уже все едет
