### ISSUE TITLE
Кинематическая модель робота - замеры

### ISSUE THREAD

**Issue by ilmirgogorev** [lsd-maddrive/mishanya-bot-project#24]
Кинематическая модель руки-манипулятора:
1. Обмерить габариты элементов звеньев руки манипулятора
2. Рассчитать передачу от перемещения линейного двигателя к угловому перемещению плеча + проверить измерение энкодеров
3. Измерить пределы перемещения линейного двигателя, поворота плечевого сустава, размаха клешни

Кинематическая модель основания:
1. Померить радиус колёс
2. Померить радиус основания(расстояние от колеса до центра)

**Comment by KaiL4eK** [comment]
- [ ] Измерить руку
- [ ] Измерить основание

**Comment by KaiL4eK** [comment]
До конца недели
