### ISSUE TITLE
Адаптировать прошивку STM F411 для STM 767ZI

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/mishanya-bot-project#53]
Нужно сделать единую прошивку. В роботе будет стоять 2 стм-ки 767, одна в нижнем основании, вторая в теле, между собой они будут соединены через CAN. 
То есть нужно взять код Антона, "переписать" его для СТМ 767, разобраться в нём, особенно в коде для силовых драйверов. Проверить, что все тесты работают.

**Comment by KaiL4eK** [comment]
@serykhelena  это готово

**Comment by serykhelena** [comment]
готово
