### ISSUE TITLE
Определиться с механикой энкодера на колеса

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/mishanya-bot-project#61]

**Comment by serykhelena** [comment]
- https://aliexpress.ru/item/1005003061099669.html?gps-id=pcStoreJustForYou&pdp_ext_f=%7B%22sku_id%22%3A%2212000023686041087%22%2C%22ship_from%22%3A%22RU%22%7D&pvid=4937926b-a8aa-4205-a297-9e1f303d4022&scm=1007.23125.137358.0&scm-url=1007.23125.137358.0&scm_id=1007.23125.137358.0&sku_id=12000023686041087&spm=a2g0o.store_pc_home.smartJustForYou_970953539.12
- https://aliexpress.ru/item/1279218186.html?spm=a2g2w.detail.1000060.3.210638cdaRZIlg&_evo_buckets=165609,165598,188871,224373,176818,194275&sku_id=5439334775&gps-id=aerPdpSubstituteRcmd&scm=1007.34525.266934.0&scm_id=1007.34525.266934.0&scm-url=1007.34525.266934.0&pvid=c7589e34-b998-4cff-8319-a2a3104fe8c5&_t=gps-id:aerPdpSubstituteRcmd,scm-url:1007.34525.266934.0,pvid:c7589e34-b998-4cff-8319-a2a3104fe8c5,tpp_buckets:24525%230%23266934%233_21387%230%23233228%238&scenario=aerPdpSubstituteRcmd&tpp_rcmd_bucket_id=266934
- https://www.chipdip.ru/product/heds-5540-a11-1

**Comment by KaiL4eK** [comment]
Последний не работает

**Comment by KaiL4eK** [comment]
Чет кажется, что надо первый заказывать, тем более из России

**Comment by serykhelena** [comment]
Вроде определились, что через ремни
