### ISSUE TITLE
Спланировать подключение рук на F767ZI

### ISSUE THREAD

**Issue by KaiL4eK** [lsd-maddrive/mishanya-bot-project#66]
Из-за блокировок основная страница с Pinout заблокирована (https://os.mbed.com/platforms/ST-Nucleo-F767ZI/) - выгрузил картинки и datasheet сюда: https://disk.yandex.ru/d/VdiUvhrjdGQnWQ

Задача - спланировать, сколько и на какие ноги подключаем драйверы.
Насколько я помню, для BB нужно 4 ноги в комплементарном режиме. То есть, всего 12 ног - 3 таймера надо найти.

Питание, полагаю, будем брать от лабораторного источника.

**Comment by serykhelena** [comment]
Пины для 1-го движка (PWM 1)
MOTOR1_PWM_LINE_HIN1 PAL_LINE(GPIOE, 11)
MOTOR1_PWM_LINE_LIN1 PAL_LINE(GPIOE, 10)
MOTOR1_PWM_LINE_HIN2 PAL_LINE(GPIOE, 13)
MOTOR1_PWM_LINE_LIN2 PAL_LINE(GPIOE, 12)

Пины для 2-го движка (PWM 8)
MOTOR2_PWM_LINE_HIN1 PAL_LINE(GPIOC, 6)
MOTOR2_PWM_LINE_LIN1 PAL_LINE(GPIOA, 5)
MOTOR2_PWM_LINE_HIN2 PAL_LINE(GPIOC, 7)
MOTOR2_PWM_LINE_LIN2 PAL_LINE(GPIOB, 0)

Пины для 3-го движка (PWM1 + PWM8)
MOTOR3_PWM_LINE_HIN1 PAL_LINE(GPIOC, 8)
MOTOR3_PWM_LINE_LIN1 PAL_LINE(GPIOB, 1)
MOTOR3_PWM_LINE_HIN2 PAL_LINE(GPIOE, 9)
MOTOR3_PWM_LINE_LIN2 PAL_LINE(GPIOE, 8)

**Comment by Doraepod** [comment]
Сверху все круто. Небольшой комментарий: для работы драйвера нужны 2 пары комплементарных ног, так что это всего два канала таймера. Но подойдет только advanced таймер, так что только 1 и 8. У каждого таймера по 4 канала, так что двумя таймерами справляемся и даже два канала остаются свободными. Но на вторую руку стм точно не хватит, разве что переписывать логику под обычные таймеры.

**Comment by serykhelena** [comment]
@Doraepod можешь подготовить пины для красного драйвера?

**Comment by Doraepod** [comment]
Думаю логично по максимум использовать те-же ноги, чтобы конфликтов поменьше было. Тогда на шесть драйверов будет так:
Левое плечо 1
PWM    GPIOE 8 TIM1_CH1
PIN1    GPIOC 8
PIN2    GPIOE 14

Левое плечо 2
PWM    GPIOE 11 TIM1_CH2
PIN1    GPIOA 5
PIN2    GPIOB 0

Левый локоть
PWM    GPIOE 13 TIM1_CH3
PIN1    GPIOB 1
PIN2    GPIOB 15

Правое плечо 1
PWM    GPIOC 6 TIM8_CH1
PIN1    GPIOE 10
PIN2    GPIOE 12

Правое плечо 2
PWM    GPIOC 7 TIM8_CH2
PIN1    GPIOD 11
PIN2    GPIOD 12

Правый локоть
PWM    GPIOC 9 TIM8_CH3
PIN1    GPIOD13
PIN2    GPIOB 2

Это все каналы первого и восьмого таймеров, включая комплиментарные, и какие-то четыре ноги, которые мне показались свободными. На них висят из интересного spi3, i2c4, канала четвертого таймера. PWM ноги должны работать в режиме канала таймера, остальные просто на выход.

**Comment by serykhelena** [comment]
Спланировано
