### ISSUE TITLE
Вопрос по обработке прерываний энкодера

### ISSUE THREAD

**Issue by Muzalevsky** [lsd-maddrive/mishanya-bot-project#99]
https://github.com/lsd-maddrive/mishanya-bot-project/blob/3786f07e95dbf1bda7ba5a31c26850f4168964b7/firmware/Base/src/encoder_base.c#L68-L70

Есть вопрос к этой строке: что если `enc_t->tic_count = MAX_TIC + 10`, тогда мы потеряем 10 меток на оборот, что много. Если гарантируется обработка прерывания при прохождении одной метки `MAX_TIC`,то моя претензия не актуальна (можно больше убрать в таком случае).

**Comment by serykhelena** [comment]
Исправлено в рамках задачи #59
